# Blog Backend CI
name: Blog Backend CI
on:
  push:
    branches:
      - master
    paths:
      - ch5/**
  pull_request:
    branches:
      - master
    paths:
      - ch5/**
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./ch5/backend/package-lock.json
      - name: Install Dependencies
        run: npm install
        working-directory: ./ch5/backend
      - name: Run linter on backend
        run: npm run lint
        working-directory: ./ch5/backend
      - name: Run backend tests
        run: npm test
        working-directory: ./ch5/backend
